#!/bin/bash

cd /opt

mkdir ExtraTools

cd ExtraTools

echo "Adding Impacket"
git clone https://github.com/SecureAuthCorp/impacket

echo "Adding LinPEAS"
git clone https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite

mkdir SecLists
echo "Adding Seclists"
git clone https://github.com/danielmiessler/SecLists

echo "Done."
